#.travis.yml

language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: always